title: "CompSoc Cookbook"
languageCode: "en-us"
theme: "i-will-rename-this-later"
relativeURLs: true

params:
  # slogan
  slogan: "Hey, good lookin', whatcha cookin'? Still testing."
  # controls where comments/new recipes are put.
  # repo requires GitHub Discussions to be enabled & Giscus applet installed
  cookbookRepo: compsoc-edinburgh/cook-book

# allergen is not a taxonomy because its functionality is different -- exclusion.
# It is implemented as simply a custom Param (identical front matter), parsed
# specially inside the filter page (/recipes).
taxonomies:
  difficulty: difficulties
  meal: meals
  tag: tags

menu:
  main:
  - identifier: recipes
    name: All recipes
    url: /recipes/
  - name: Github
    url: https://github.com/compsoc-edinburgh/cook-book

outputs:
  section: ["html", "json"]
