title: "CompSoc Cookbook"
languageCode: "en-us"
theme: "cookbook-theme"

params:
  # slogan
  slogan: "Hey, good lookin', whatcha got cookin'?"
  # controls where all links to GitHub link to.
  cookbookRepo: compsoc-edinburgh/cook-book
  # 14 allergens, that recipes can use
  allergens:
    - celery
    - gluten
    - crustaceans
    - eggs
    - fish
    - lupin
    - milk
    - molluscs
    - mustard
    - nuts
    - peanuts
    - sesame_seeds
    - soya
    - sulphites
  # URLencoded template github new file
  templateRecipe: |
    ---
    keywords: [babylonian, fresh, vegetarian, thisisoptional]
    allergens: [milk, gluten, celery, crustaceans, eggs, fish, lupin, milk, molluscs, mustard, nuts, peanuts, sesame_seeds, soya, sulphites]
    serves: 30 cookies
    prep time: 15 mins
    anything you want: father
    ---

    # Grandma's Milk Chocolate Cookies

    They always turn out delicious!

    ## Ingredients

    * 30g of molten hearts
    * 70g of unsalted butter
    * 100ml milk

    ## Blahblah

    whatever markdown you want

# allergen is not a taxonomy because its functionality is different -- exclusion.
# It is implemented as simply a custom Param (identical front matter), parsed
# specially inside the filter page (/recipes).
taxonomies:
  difficulty: difficulties
  meal: meals
  tag: tags

menu:
  main:
  - identifier: recipes
    name: All recipes
    url: /recipes/
  - name: Github
    url: https://github.com/compsoc-edinburgh/cook-book

outputs:
  section: ["html", "json"]
