title: "CompSoc Cookbook"
languageCode: "en-us"
theme: "cookbook-theme"
relativeURLs: true

params:
  # slogan
  slogan: "Hey, good lookin', whatcha got cookin'?"
  # controls where all links to GitHub link to. Comments are not controlled by
  # this since they also require a hash ID: go into comments.html to change the
  # repo.
  cookbookRepo: compsoc-edinburgh/cook-book

# allergen is not a taxonomy because its functionality is different -- exclusion.
# It is implemented as simply a custom Param (identical front matter), parsed
# specially inside the filter page (/recipes).
taxonomies:
  difficulty: difficulties
  meal: meals
  tag: tags

menu:
  main:
  - identifier: recipes
    name: All recipes
    url: /recipes/
  - name: Github
    url: https://github.com/compsoc-edinburgh/cook-book

outputs:
  section: ["html", "json"]
