title: "CompSoc Cookbook"
languageCode: "en-us"
slogan: "Hey, good lookin', whatcha cookin'? Still testing."
theme: "i-will-rename-this-later"
relativeURLs: true

params:
  # controls where the comments are put.
  commentRepo: yutotakano/cook-book

taxonomies:
  difficulty: difficulties
  cuisine: cuisines
  dietarypref: dietaryprefs
