title: "CompSoc Cookbook"
languageCode: "en-us"
theme: "i-will-rename-this-later"
relativeURLs: true

params:
  # slogan
  slogan: "Hey, good lookin', whatcha cookin'? Still testing."
  # controls where comments/new recipes are put.
  cookbookRepo: compsoc-edinburgh/cook-book

taxonomies:
  difficulty: difficulties
  meal: meals
  allergen: allergens
  tag: tags

menu:
  main:
  - identifier: recipes
    name: All recipes
    url: /recipes/
  - name: Github
    url: https://github.com/compsoc-edinburgh/cook-book

