title: "CompSoc Cookbook"
languageCode: "en-us"
theme: "i-will-rename-this-later"
relativeURLs: true

params:
  # slogan
  slogan: "Hey, good lookin', whatcha cookin'? Still testing."
  # controls where the comments are put.
  commentRepo: yutotakano/cook-book

taxonomies:
  difficulty: difficulties
  cuisine: cuisines
  tag: tags
